// ── Template generators ──────────────────────────────────
// Turns the neutral layout spec extracted from a publisher's InDesign IDML
// (see services/idml) into a Scribus (.sla) or LaTeX (.cls) template scaffold.
// The scaffold intentionally targets ~80% fidelity: geometry, columns, colors
// and named styles port automatically; a designer finalizes decorative details
// once per journal.

export interface LayoutSpec {
  units?: string
  pageWidth: number
  pageHeight: number
  facingPages?: boolean
  marginTop: number
  marginBottom: number
  marginLeft: number
  marginRight: number
  bleedTop?: number
  bleedBottom?: number
  bleedInside?: number
  bleedOutside?: number
  columnCount: number
  columnGutter: number
  fonts?: string[]
  colors?: Array<{ name: string; space: string | null; values: number[] }>
  paragraphStyles?: Array<{
    name: string
    fontFamily: string | null
    fontSize: number | null
    leading: number | null
    alignment: string | null
    spaceBefore?: number
    spaceAfter?: number
    firstLineIndent?: number
  }>
  characterStyles?: Array<{
    name: string
    fontFamily: string | null
    fontSize: number | null
  }>
}

const xml = (s: string) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')

// IDML Justification → Scribus ALIGN (0 left, 1 center, 2 right, 3 justify, 4 forced)
function slaAlign(justification: string | null): number {
  switch (justification) {
    case 'CenterAlign': return 1
    case 'RightAlign': return 2
    case 'LeftJustified':
    case 'RightJustified':
    case 'CenterJustified': return 3
    case 'FullyJustified': return 4
    default: return 0
  }
}

/** Generate a minimal but valid Scribus 1.5 .sla template from the spec. */
export function generateScribusSla(spec: LayoutSpec, templateName: string): string {
  const defaultFont = spec.fonts?.[0] ?? 'Arial Regular'

  const colorDefs = (spec.colors ?? [])
    .map((c) => {
      if (c.space === 'CMYK' && c.values.length === 4) {
        const [cc, m, y, k] = c.values
        return `    <COLOR NAME="${xml(c.name)}" SPACE="CMYK" C="${cc}" M="${m}" Y="${y}" K="${k}"/>`
      }
      if (c.space === 'RGB' && c.values.length === 3) {
        const hex = c.values.map((v) => Math.round(v).toString(16).padStart(2, '0')).join('')
        return `    <COLOR NAME="${xml(c.name)}" SPACE="RGB" RGB="#${hex}"/>`
      }
      return null
    })
    .filter(Boolean)
    .join('\n')

  const styleDefs = (spec.paragraphStyles ?? [])
    .map((s) => {
      const font = s.fontFamily ?? defaultFont
      const size = s.fontSize ?? 10
      const leading = s.leading ?? size * 1.2
      return (
        `    <STYLE NAME="${xml(s.name)}" DefaultStyle="0" ALIGN="${slaAlign(s.alignment)}" ` +
        `LINESPMode="0" LINESP="${leading}" INDENT="0" FIRST="${s.firstLineIndent ?? 0}" ` +
        `VOR="${s.spaceBefore ?? 0}" NACH="${s.spaceAfter ?? 0}" ` +
        `FONT="${xml(font)}" FONTSIZE="${size}"/>`
      )
    })
    .join('\n')

  const cols = spec.columnCount
  const frameX = spec.marginLeft
  const frameY = spec.marginTop
  const frameW = spec.pageWidth - spec.marginLeft - spec.marginRight
  const frameH = spec.pageHeight - spec.marginTop - spec.marginBottom

  return `<?xml version="1.0" encoding="UTF-8"?>
<SCRIBUSUTF8NEW Version="1.5.8">
  <!-- Generated by PubFlow template-port bot: ${xml(templateName)} -->
  <!-- Source: publisher InDesign layout (IDML). Review before production use. -->
  <DOCUMENT ANZPAGES="1" PAGEWIDTH="${spec.pageWidth}" PAGEHEIGHT="${spec.pageHeight}"
    BORDERLEFT="${spec.marginLeft}" BORDERRIGHT="${spec.marginRight}"
    BORDERTOP="${spec.marginTop}" BORDERBOTTOM="${spec.marginBottom}"
    BleedTop="${spec.bleedTop ?? 0}" BleedBottom="${spec.bleedBottom ?? 0}"
    BleedLeft="${spec.bleedInside ?? 0}" BleedRight="${spec.bleedOutside ?? 0}"
    UNITS="0" DFONT="${xml(defaultFont)}" DSIZE="10"
    ORIENTATION="${spec.pageWidth > spec.pageHeight ? 1 : 0}"
    PAGESIZE="Custom" FIRSTNUM="1" BOOK="${spec.facingPages ? 1 : 0}"
    AUTOSPALTEN="${cols}" ABSTSPALTEN="${spec.columnGutter}">
${colorDefs}
${styleDefs}
    <MASTERPAGE PAGEXPOS="0" PAGEYPOS="0" PAGEWIDTH="${spec.pageWidth}" PAGEHEIGHT="${spec.pageHeight}"
      BORDERLEFT="${spec.marginLeft}" BORDERRIGHT="${spec.marginRight}"
      BORDERTOP="${spec.marginTop}" BORDERBOTTOM="${spec.marginBottom}"
      NUM="0" NAM="Normal" MNAM="" HorizontalGuides="" VerticalGuides=""/>
    <PAGE PAGEXPOS="0" PAGEYPOS="0" PAGEWIDTH="${spec.pageWidth}" PAGEHEIGHT="${spec.pageHeight}"
      BORDERLEFT="${spec.marginLeft}" BORDERRIGHT="${spec.marginRight}"
      BORDERTOP="${spec.marginTop}" BORDERBOTTOM="${spec.marginBottom}"
      NUM="0" NAM="" MNAM="Normal" HorizontalGuides="" VerticalGuides=""/>
    <PAGEOBJECT XPOS="${frameX}" YPOS="${frameY}" WIDTH="${frameW}" HEIGHT="${frameH}"
      OwnPage="0" ItemID="1" PTYPE="4" ANNAME="MainTextFrame"
      COLUMNS="${cols}" COLGAP="${spec.columnGutter}"
      NEXTITEM="-1" BACKITEM="-1">
      <StoryText>
        <DefaultStyle/>
        <ITEXT CH=""/>
        <trail/>
      </StoryText>
    </PAGEOBJECT>
  </DOCUMENT>
</SCRIBUSUTF8NEW>
`
}

import { normalizeTemplateClassName } from '@pubflow/types'

// Proper LaTeX escaping (mirrors processors/issue.ts's texEscape) — this
// previously stripped special characters instead of escaping them, so a
// style/font name like "Smith & Sons" silently lost the "&" instead of
// becoming "Smith \& Sons".
const TEX_ESCAPES: Record<string, string> = {
  '\\': '\\textbackslash{}',
  '&': '\\&', '%': '\\%', '$': '\\$', '#': '\\#',
  '_': '\\_', '{': '\\{', '}': '\\}',
  '~': '\\textasciitilde{}', '^': '\\textasciicircum{}',
}
const texEscape = (s: string) => s.replace(/[\\&%$#_{}~^]/g, (ch) => TEX_ESCAPES[ch] as string)
const macroName = (s: string) =>
  s.replace(/[^a-zA-Z]/g, '') || 'Unnamed'

// LaTeX \newcommand names must be pure letters, so numbered/punctuated IDML
// style names (e.g. "Body Text 1" / "Body Text 2") can collapse onto the
// same macroName and collide. Track names already handed out in this
// generation run and disambiguate with an all-letter suffix (A, B, ... Z,
// AA, ...) instead of silently overwriting the earlier \newcommand.
function makeUniqueNamer() {
  const seen = new Map<string, number>()
  return (raw: string): string => {
    const base = macroName(raw)
    const count = seen.get(base) ?? 0
    seen.set(base, count + 1)
    if (count === 0) return base
    let n = count
    let suffix = ''
    do {
      suffix = String.fromCharCode(65 + ((n - 1) % 26)) + suffix
      n = Math.floor((n - 1) / 26)
    } while (n > 0)
    return base + suffix
  }
}

/** Generate a LaTeX class scaffold (.cls) from the spec. */
export function generateLatexClass(spec: LayoutSpec, templateName: string): string {
  const pt = (v: number) => `${(Math.round(v * 100) / 100)}pt`
  const mainFont = spec.fonts?.[0]
  const uniqueColorName = makeUniqueNamer()
  const uniqueStyleName = makeUniqueNamer()

  const colorDefs = (spec.colors ?? [])
    .map((c) => {
      const name = uniqueColorName(c.name)
      // IDML stores CMYK as 0–100; xcolor's cmyk model expects 0–1.
      if (c.space === 'CMYK' && c.values.length === 4)
        return `\\definecolor{${name}}{cmyk}{${c.values.map((v) => (v / 100).toFixed(3)).join(',')}}`
      if (c.space === 'RGB' && c.values.length === 3)
        return `\\definecolor{${name}}{RGB}{${c.values.map((v) => Math.round(v)).join(',')}}`
      return null
    })
    .filter(Boolean)
    .join('\n')

  const styleMacros = (spec.paragraphStyles ?? [])
    .map((s) => {
      const name = uniqueStyleName(s.name)
      const size = s.fontSize ?? 10
      const leading = s.leading ?? size * 1.2
      const parts = [`\\fontsize{${size}pt}{${leading}pt}\\selectfont`]
      if (s.alignment === 'CenterAlign') parts.push('\\centering')
      else if (s.alignment === 'RightAlign') parts.push('\\raggedleft')
      else if (s.alignment === 'LeftAlign') parts.push('\\raggedright')
      return (
        `% IDML paragraph style: ${texEscape(s.name)}` +
        `\n\\newcommand{\\style${name}}[1]{{${parts.join(' ')} #1\\par}}`
      )
    })
    .join('\n')

  return `%% ${templateName}.cls — generated by PubFlow template-port bot
%% Source: publisher layout (${spec.units ?? 'pt'} units). Review before production use.
\\NeedsTeXFormat{LaTeX2e}
\\ProvidesClass{${normalizeTemplateClassName(templateName)}}[2026/07/05 PubFlow ported publisher layout]

\\LoadClass[10pt]{article}

\\RequirePackage[
  paperwidth=${pt(spec.pageWidth)},
  paperheight=${pt(spec.pageHeight)},
  top=${pt(spec.marginTop)},
  bottom=${pt(spec.marginBottom)},
  left=${pt(spec.marginLeft)},
  right=${pt(spec.marginRight)}${spec.facingPages ? ',\n  twoside' : ''}
]{geometry}
\\RequirePackage{xcolor}
\\RequirePackage{graphicx}
${spec.columnCount > 1 ? `\\RequirePackage{multicol}\n\\setlength{\\columnsep}{${pt(spec.columnGutter)}}` : ''}
\\RequirePackage{fontspec} % compile with XeLaTeX/LuaLaTeX
${mainFont ? `\\IfFontExistsTF{${texEscape(mainFont)}}{\\setmainfont{${texEscape(mainFont)}}}{}` : ''}

% ── Publisher colors ─────────────────────────────────────
${colorDefs || '% (no named colors found in source layout)'}

% ── Publisher paragraph styles ───────────────────────────
${styleMacros || '% (no paragraph styles found in source layout)'}

${spec.columnCount > 1
  ? `% Body flows in ${spec.columnCount} columns — wrap content:\n% \\begin{multicols}{${spec.columnCount}} ... \\end{multicols}`
  : ''}
\\endinput
`
}
